### ISSUE TITLE
/usr/sbin/autoshutdown: Zeile 924: 0.00: Syntaxfehler: Ungültiger arithmetischer Operator. (Fehlerverursachendes Zeichen ist ".00").

### ISSUE THREAD

**Issue by menotuu** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#117] opened 2022-02-24 10:55 UTC
iam using a fork of openmediavault-autoshutdown on a 64bit Raspberry Pi4 with Kernel 5.10 and Debian 11 (bullseye)
from https://github.com/mnul/debian-autoshutdown

my problem is, the tool doesnt check the configured 6 cycles, but gives error when dl rate is lower than configured but gives than a error and shutdown instantly! is the dl rate higher than configured, the check is working correctly and its not shuting down.

i dont know, how to solve it.

Feb 24 11:37:27 Raspberry4NAS autoshutdown[1169]: root: INFO: '_check_ul_dl_rate(): Network interface: eth0 (last 43592s) DL: 0,6 kB/s, UL: 0,1 kB/s under 20 kB/s -> next check'
Feb 24 11:37:27 Raspberry4NAS autoshutdown[1169]: /usr/sbin/autoshutdown: Zeile 924: 0.00: Syntaxfehler: Ungültiger arithmetischer Operator. (Fehlerverursachendes Zeichen ist ".00").
Feb 24 11:37:27 Raspberry4NAS autoshutdown[1169]: root: INFO: 'main(): All active checks passed, Shutting down system ...'

this is my log
https://paste.kodi.tv/qufitevadi.kodi

this is my config
https://paste.kodi.tv/ogesusoxuq.kodi

this is the bin
https://paste.kodi.tv/lecosuwupo.kodi

**Comment by nrandon** [comment] 2022-02-24 20:53
@menotuu hi, you need to update the the latest script to run on bullseye. so ether replace you current script with this (should be compatible if the script was not modified by mnul (https://raw.githubusercontent.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown/master/usr/sbin/autoshutdown) or get mnul to do an update (the fix relating to the problem is this: https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown/commit/78a7b58784e57eaf20db02d94a5cfe9a6f808afb)

**Comment by nrandon** [comment] 2022-02-24 20:54
closing issue as it not OMV related and is on a unsupported folk

**Closed by nrandon** 2022-02-24 20:54 UTC
