### ISSUE TITLE
typos in logs

### ISSUE THREAD

**Issue by thatso** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#86] opened 2021-02-03 22:38 UTC
I've spotted some typos in the logs. You might want to correct line 1335 in `/usr/sbin/autoshutdown`:

`_log "INFO: Waiting 5 minuets until the first check"`

to

`_log "INFO: Waiting 5 minutes until the first check"`

and line 1136:

` _log "INFO: Finding available network interfaces and there IPv4 addresses"`

to

` _log "INFO: Finding available network interfaces and their IPv4 addresses"`

Maybe also change line 1354:

`_log "INFO: All active check passed, ${FCNT} cycles until shutdown..."`

to

`_log "INFO: All active checks passed, ${FCNT} cycles until shutdown..."`

**Comment by thatso** [comment] 2021-02-07 23:36
Friendly reminder: only the first typo was corrected.

**Comment by nrandon** [comment] 2021-02-08 13:14
My apology i did see the other changes required I have re-open and will fix in the next update

**Comment by nrandon** [comment] 2021-02-08 13:52
fixed in 5.1.9

**Closed by nrandon** 2021-02-08 13:52 UTC

**Comment by thatso** [comment] 2021-02-08 13:54
Much appreciated. Please concentrate on #87 first, some typos can very well wait.  :-)

**Comment by ryecoaaron** [comment] 2021-02-08 14:11
@thatso I know the typos could wait but I figured if I was pushing out a new package that we might as well get the typo fix in too.    The 87 issue was caused by the my automation that builds the package.
